# Generated by Django 4.2.1 on 2026-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0008_spsahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='auto_schedule',
            field=models.CharField(default='NONE', max_length=16),
        ),
        migrations.AlterField(
            model_name='spsahistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
