# Generated by Django 4.2.1 on 2026-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0009_test_auto_schedule_alter_spsahistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
